# Generated by Django 2.2.6 on 2019-10-27 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('points', models.PositiveIntegerField(verbose_name='Points')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='LastLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=30, default=0, max_digits=50, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=30, default=0, max_digits=50, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_infected', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Percentage of infected survivors')),
                ('per_not_infected', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Percentage of non-infected survivors')),
                ('average_water', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Average amount of waters by survivor')),
                ('average_food', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Average amount of foods by survivor')),
                ('average_medication', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Average amount of medication by survivor')),
                ('average_ammunition', models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Average amount of ammunition by survivor')),
                ('lost_points', models.PositiveIntegerField(null=True, verbose_name='Points lost because of infected survivor')),
            ],
        ),
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('age', models.PositiveIntegerField(verbose_name='Age')),
                ('gender', models.CharField(max_length=25, verbose_name='Gender')),
                ('infected', models.BooleanField(default=False, verbose_name='Infected')),
                ('reported_infected', models.PositiveIntegerField(default=0, verbose_name='Reported Infected')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Inventory')),
                ('last_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.LastLocation')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(to='backend.Item'),
        ),
    ]
